# Generated by Django 5.0.1 on 2025-05-22 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Package name (e.g., 'Basic Package', 'Premium Package')", max_length=100)),
                ('description', models.TextField(blank=True, help_text="Details about what's included in this package")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the selection')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.service')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('service', 'name')},
            },
        ),
    ]
