# Generated by Django 5.0.1 on 2025-05-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_create_catering_category'),
        ('services', '0002_servicepackage'),
    ]

    operations = [
    ]
