# Generated by Django 5.0.1 on 2025-05-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_merge_20250526_1742'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['base_price'], name='idx_service_base_price'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='idx_service_name'),
        ),
    ]
