# Generated by Django 5.0.1 on 2025-05-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_add_service_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['provider', 'status'], name='idx_provider_status'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_featured'], name='idx_service_featured'),
        ),
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['rating'], name='idx_service_review_rating'),
        ),
    ]
