# Generated by Django 5.0.1 on 2025-06-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='service',
            name='idx_service_base_price',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='idx_service_name',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='idx_provider_status',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='idx_service_featured',
        ),
        migrations.RemoveIndex(
            model_name='servicereview',
            name='idx_service_review_rating',
        ),
        migrations.AddField(
            model_name='service',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact phone number for this service', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email for this service', max_length=254),
        ),
    ]
