# Generated by Django 5.0.1 on 2025-12-30 13:43

from django.db import migrations, models


def migrate_service_pricing_data(apps, schema_editor):
    """Migrate existing base_price and price_type data to new pricing structure"""
    Service = apps.get_model('services', 'Service')
    for service in Service.objects.all():
        # Check price_type to determine if hourly or flat
        price_type_lower = service.price_type.lower() if service.price_type else ''
        
        if 'hour' in price_type_lower or 'hr' in price_type_lower or 'hourly' in price_type_lower:
            # Migrate to hourly pricing
            service.pricing_type = 'HOURLY'
            service.hourly_price = service.base_price
            service.flat_price = None
        else:
            # Default to flat pricing for "flat rate", "per person", etc.
            service.pricing_type = 'FLAT'
            service.flat_price = service.base_price
            service.hourly_price = None
        
        service.save(update_fields=['pricing_type', 'hourly_price', 'flat_price'])


def reverse_service_pricing_data(apps, schema_editor):
    """Reverse migration: restore base_price and price_type"""
    Service = apps.get_model('services', 'Service')
    for service in Service.objects.all():
        if service.pricing_type == 'HOURLY' and service.hourly_price:
            service.base_price = service.hourly_price
            service.price_type = 'Per hour'
        elif service.pricing_type == 'FLAT' and service.flat_price:
            service.base_price = service.flat_price
            service.price_type = 'Flat rate'
        service.save(update_fields=['base_price', 'price_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_service_idx_service_base_price_and_more'),
    ]

    operations = [
        # Step 1: Add new fields (nullable initially)
        migrations.AddField(
            model_name='service',
            name='flat_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat rate price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='hourly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per hour', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_type',
            field=models.CharField(choices=[('HOURLY', 'Hourly Rate'), ('FLAT', 'Flat Rate')], default='HOURLY', max_length=10),
        ),
        # Step 2: Migrate data from old fields to new fields
        migrations.RunPython(migrate_service_pricing_data, reverse_service_pricing_data),
        # Step 3: Remove old fields
        migrations.RemoveField(
            model_name='service',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_type',
        ),
    ]
