# Generated by Django 5.0.1 on 2025-05-25 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingservice_package'),
    ]

    operations = [
    ]
