# Generated by Django 5.0.1 on 2025-05-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20250525_2126'),
    ]

    operations = [
    ]
