# Generated by Django 5.0.1 on 2025-05-25 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20250525_2131'),
        ('venues', '0004_delete_venuecateringpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('venue', 'Venue Booking'), ('service_only', 'Service Only')], default='venue', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.venue'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='venue_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
