# Generated by Django 5.0.1 on 2025-05-26 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_booking_type_alter_booking_venue_and_more'),
        ('venues', '0005_venuecateringpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='uses_venue_catering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue_catering_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue_catering_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue_catering_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='venues.venuecateringpackage'),
        ),
    ]
