# Generated by Django 5.0.1 on 2025-05-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_uses_venue_catering_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status'], name='idx_booking_payment_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'event_date'], name='idx_booking_user_event_date'),
        ),
    ]
