# Generated by Django 5.0.1 on 2025-05-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_add_booking_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_type'], name='idx_booking_type'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'payment_status'], name='idx_user_payment_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['venue', 'status'], name='idx_venue_status'),
        ),
    ]
