# Generated by Django 5.0.1 on 2025-06-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='idx_booking_payment_status',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='idx_booking_user_event_date',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='idx_booking_type',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='idx_user_payment_status',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='idx_venue_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='quoted_message',
            field=models.TextField(blank=True, help_text='Admin message for the quotation', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='quotation', max_length=20),
        ),
    ]
