# Generated by Django 5.0.1 on 2025-06-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_remove_booking_idx_booking_payment_status_and_more'),
    ]

    operations = [
        # Update STATUS_CHOICES to include 'quotation'
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(
                choices=[
                    ('quotation', 'Quotation'),
                    ('pending', 'Pending'),
                    ('confirmed', 'Confirmed'),
                    ('cancelled', 'Cancelled'),
                    ('completed', 'Completed')
                ], 
                default='quotation', 
                max_length=20
            ),
        ),
    ]
