# Generated by Django 5.0.1 on 2025-05-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='category',
        ),
        migrations.AddField(
            model_name='venue',
            name='category',
            field=models.ManyToManyField(related_name='venues', to='venues.venuecategory'),
        ),
    ]
