# Generated by Django 5.0.1 on 2025-05-25 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_remove_venue_category_venue_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueCateringPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(default='per person', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_packages', to='venues.venue')),
            ],
            options={
                'ordering': ['price', 'name'],
                'unique_together': {('venue', 'name')},
            },
        ),
    ]
