# Generated by Django 5.0.1 on 2025-05-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venuecateringpackage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VenueCateringPackage',
        ),
    ]
