# Generated by Django 5.0.1 on 2025-05-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_venuecateringpackage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['name'], name='idx_venue_name'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['price_per_hour'], name='idx_venue_price'),
        ),
    ]
