# Generated by Django 5.0.1 on 2025-05-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_add_venue_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['is_featured'], name='idx_venue_featured'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['owner'], name='idx_venue_owner'),
        ),
        migrations.AddIndex(
            model_name='venuereview',
            index=models.Index(fields=['rating'], name='idx_venue_review_rating'),
        ),
    ]
