# Generated by Django 5.0.1 on 2025-06-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='venue',
            name='idx_venue_name',
        ),
        migrations.RemoveIndex(
            model_name='venue',
            name='idx_venue_price',
        ),
        migrations.RemoveIndex(
            model_name='venue',
            name='idx_venue_featured',
        ),
        migrations.RemoveIndex(
            model_name='venue',
            name='idx_venue_owner',
        ),
        migrations.RemoveIndex(
            model_name='venuereview',
            name='idx_venue_review_rating',
        ),
        migrations.AddField(
            model_name='venue',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact phone number for this venue', max_length=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email for this venue', max_length=254),
        ),
    ]
