# Generated by Django 5.0.1 on 2025-12-30 13:43

from django.db import migrations, models


def migrate_venue_pricing_data(apps, schema_editor):
    """Migrate existing price_per_hour data to new pricing structure"""
    Venue = apps.get_model('venues', 'Venue')
    for venue in Venue.objects.all():
        # All existing venues assumed hourly pricing
        venue.pricing_type = 'HOURLY'
        venue.hourly_price = venue.price_per_hour
        venue.flat_price = None
        venue.save(update_fields=['pricing_type', 'hourly_price', 'flat_price'])


def reverse_venue_pricing_data(apps, schema_editor):
    """Reverse migration: restore price_per_hour from hourly_price"""
    Venue = apps.get_model('venues', 'Venue')
    for venue in Venue.objects.all():
        if venue.pricing_type == 'HOURLY' and venue.hourly_price:
            venue.price_per_hour = venue.hourly_price
        elif venue.pricing_type == 'FLAT' and venue.flat_price:
            venue.price_per_hour = venue.flat_price  # Best effort
        venue.save(update_fields=['price_per_hour'])


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_remove_venue_idx_venue_name_and_more'),
    ]

    operations = [
        # Step 1: Add new fields (nullable initially)
        migrations.AddField(
            model_name='venue',
            name='flat_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat rate price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='hourly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per hour', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='pricing_type',
            field=models.CharField(choices=[('HOURLY', 'Hourly Rate'), ('FLAT', 'Flat Rate')], default='HOURLY', max_length=10),
        ),
        # Step 2: Migrate data from old fields to new fields
        migrations.RunPython(migrate_venue_pricing_data, reverse_venue_pricing_data),
        # Step 3: Remove old field
        migrations.RemoveField(
            model_name='venue',
            name='price_per_hour',
        ),
    ]
