# Generated by Django 5.0.1 on 2026-01-09 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0010_remove_old_price_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['is_featured', 'status'], name='venues_venu_is_feat_e129ed_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['-created_at'], name='venues_venu_created_e94816_idx'),
        ),
    ]
